[tool.poetry]
name = "deezer-downloader"
version = "2.0.0-1"
description = "download music from Deezer with a nice front end"
authors = ["kmille <github@androidloves.me>"]
readme = "README.md"
packages = [{include = "deezer_downloader"}]
repository = "https://github.com/kmille/deezer-downloader"
homepage = "https://github.com/kmille/deezer-downloader"


[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.28.1"
flask = "^2.2.2"
python-mpd2 = "^3.0.5"

pycryptodome = "^3.16.0"
jinja2 = "^3.1.2"
flask-autoindex = "^0.6.6"
giphypop = "^0.3"
waitress = "^2.1.2"


[tool.poetry.group.dev.dependencies]
pdbpp = "^0.10.3"
pytest = "^7.2.0"
python-magic = "^0.4.27"
flake8 = "^6.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
deezer-downloader = 'deezer_downloader.cli.runner:main'

[tool.setuptools.package-data]
deezer_downloader = ["cli/settings.ini.template"]
